### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by MaximilianFlechtner** [bkuhl/laravel-fpm-nginx#5]
When I try to view the page in my browser i get no response. (localhost:80).

**Comment by MaximilianFlechtner** [comment]
I have used your example Dockerfiel

**Comment by morganlaneap** [comment]
The solution to this is to copy the `default.conf` into your project and add:

```
# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf
```
 
to your Dockerfile.
